# Generated by Django 3.2.5 on 2021-07-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=29)),
                ('identify_card_no', models.CharField(max_length=19)),
                ('award_point', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12)),
                ('email_address', models.CharField(max_length=34)),
                ('post_number', models.IntegerField()),
                ('notes', models.CharField(max_length=560)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategories',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=33)),
                ('price', models.IntegerField()),
                ('notes', models.CharField(max_length=568)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRentals',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('create_at', models.DateField()),
                ('start_at', models.DateField()),
                ('check_out_at', models.CharField(max_length=19)),
                ('summary', models.CharField(max_length=487)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=568)),
                ('unit_price', models.CharField(max_length=86)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=34)),
                ('post_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=32)),
                ('phone_no', models.CharField(max_length=12)),
                ('identity_card_no', models.CharField(max_length=19)),
                ('address', models.CharField(max_length=42)),
                ('is_manager', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=36)),
                ('descriptions', models.CharField(max_length=548)),
                ('is_available', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('is_canceled', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('detail', models.CharField(max_length=557)),
                ('rental', models.ForeignKey(db_column='rental', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomrentals')),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.servicetypes')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('floors', models.IntegerField()),
                ('number', models.IntegerField()),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.roomcategories')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.status')),
            ],
        ),
        migrations.AddField(
            model_name='roomrentals',
            name='room',
            field=models.ForeignKey(db_column='room', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.rooms'),
        ),
        migrations.AddField(
            model_name='roomrentals',
            name='staff_create',
            field=models.ForeignKey(db_column='staff_create', on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.staff'),
        ),
    ]
